### ISSUE TITLE
Multiple questions in dissertation.sty

### ISSUE THREAD

**Issue by BrushXue** [LehighISE/Dissertation#2]
First of all thank you for creating this repo. It really saved me a lot of time.

A few questions and recommendations:
1. In this PR https://github.com/LehighISE/Dissertation/pull/1 the header was added. However I was notified by the Graduate Program Administrator that the header in my dissertation needs to be removed.

2. For page margin, should I keep the page number in the 1in margin?
```latex
\geometry{left=1.5in,right=1in,top=1in,bottom=1in,includefoot}
```

3. To enable `\par` in the acknowledgment section, add `\long` to the definition:
```
\long\def\prefacesection#1#2{
```

Let me know if you want me to send a PR for these changes.

**Comment by frankecurtis** [comment]
Thank you for the comments.  No need to submit a pull request.  You can make your changes in your repository.  We will conisder an update of this repository at a later time.
