### ISSUE TITLE
Copyright page format

### ISSUE THREAD

**Issue by BrushXue** [LehighISE/Dissertation#3]
Sorry to bother you again!

Here's another round of feedback from the graduate program administrator:

> The copyright page It should say
> @ 2024 Copyright

Therefore in `dissertation.sty`
https://github.com/LehighISE/Dissertation/blob/339de60ecafa6c9ba44e6ac65dde780e6ab33b18/src/dissertation.sty#L91
it should be
```latex
    \copyright\@copyrightyear\ Copyright \\
```

**Comment by frankecurtis** [comment]
This has been fixed.
